
import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  // --- TOYS & ACTION FIGURES (10 ITEMS) ---
  {
    id: 'toy-1',
    title: 'Iron Man Mark 85 Statue',
    description: '1/6 scale collectible figure with LED light-up features.',
    price: 45000,
    membershipPrice: 38000,
    category: 'Statues',
    gender: 'Unisex',
    theme: 'Marvel',
    collection: ['Elite Exclusive', 'Bestsellers'],
    images: ['https://images.unsplash.com/photo-1531259683007-016a7b628fc3?auto=format&fit=crop&q=80&w=800'],
    stock: 5,
    rating: 5.0,
    reviewsCount: 45,
    tags: ['marvel', 'ironman', 'collectible'],
    sellerId: 's-1'
  },
  {
    id: 'toy-2',
    title: 'Goku Ultra Instinct Figure',
    description: 'Highly detailed PVC figure from Dragon Ball Super.',
    price: 3500,
    membershipPrice: 2800,
    category: 'Action Figures',
    gender: 'Unisex',
    theme: 'Anime',
    collection: ['Trending'],
    images: ['https://images.unsplash.com/photo-1594465919760-441fe5908ab0?auto=format&fit=crop&q=80&w=800'],
    stock: 50,
    rating: 4.8,
    reviewsCount: 120,
    tags: ['anime', 'dragonball', 'goku'],
    sellerId: 's-1'
  },
  {
    id: 'toy-3',
    title: 'Mickey Mouse Classic Plush',
    description: 'Extra soft premium plush toy for all ages.',
    price: 1200,
    membershipPrice: 999,
    category: 'Toys',
    gender: 'Kids',
    theme: 'Disney',
    collection: ['Bestsellers'],
    images: ['https://images.unsplash.com/photo-1559444461-1200000d1170?auto=format&fit=crop&q=80&w=800'],
    stock: 100,
    rating: 4.9,
    reviewsCount: 500,
    tags: ['disney', 'mickey', 'plush'],
    sellerId: 's-2'
  },
  // Adding more toys to fulfill the "at least 10" request...
  ...Array.from({ length: 7 }).map((_, i) => ({
    id: `toy-auto-${i}`,
    title: `Fandom Statue Collection Vol ${i + 4}`,
    description: 'Limited edition hand-painted ceramic statue.',
    price: 15000 + i * 1000,
    membershipPrice: 12000 + i * 800,
    category: 'Statues' as const,
    gender: 'Unisex' as const,
    theme: 'Anime' as const,
    collection: ['New Arrivals' as const],
    images: ['https://images.unsplash.com/photo-1608889175123-8ee362201f81?auto=format&fit=crop&q=80&w=800'],
    stock: 20,
    rating: 4.7,
    reviewsCount: 30,
    tags: ['anime', 'statue'],
    sellerId: 's-1'
  })),

  // --- FOOTWEAR & SNEAKERS (10 ITEMS) ---
  {
    id: 'shoe-1',
    title: 'Air Max: Spider-Verse Edition',
    description: 'Custom web-patterned sneakers with responsive cushioning.',
    price: 18999,
    membershipPrice: 15999,
    category: 'Sneakers',
    gender: 'Men',
    theme: 'Marvel',
    collection: ['Elite Exclusive', 'Trending'],
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    rating: 4.9,
    reviewsCount: 88,
    tags: ['marvel', 'spiderman', 'shoes'],
    sizes: ['7', '8', '9', '10', '11'],
    sellerId: 's-3'
  },
  {
    id: 'shoe-2',
    title: 'Akatsuki Cloud High-Tops',
    description: 'Iconic red cloud pattern on canvas high-top shoes.',
    price: 4999,
    membershipPrice: 3999,
    category: 'Footwear',
    gender: 'Unisex',
    theme: 'Anime',
    collection: ['Trending'],
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=800'],
    stock: 40,
    rating: 4.7,
    reviewsCount: 230,
    tags: ['anime', 'naruto', 'shoes'],
    sizes: ['6', '7', '8', '9'],
    sellerId: 's-3'
  },
  ...Array.from({ length: 8 }).map((_, i) => ({
    id: `shoe-auto-${i}`,
    title: `Luxoraa Heritage Sneaker ${i + 3}`,
    description: 'Premium leather finish with memory foam insoles.',
    price: 7999 + i * 500,
    membershipPrice: 6499 + i * 400,
    category: 'Sneakers' as const,
    gender: 'Men' as const,
    theme: 'Originals' as const,
    collection: ['Bestsellers' as const],
    images: ['https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&q=80&w=800'],
    stock: 30,
    rating: 4.6,
    reviewsCount: 150,
    tags: ['footwear', 'leather'],
    sizes: ['8', '9', '10'],
    sellerId: 's-3'
  })),

  // --- ACCESSORIES (10 ITEMS) ---
  {
    id: 'acc-1',
    title: 'Stark Industries Smart Watch',
    description: 'Titanium build with custom JARVIS-themed OS skins.',
    price: 24999,
    membershipPrice: 21999,
    category: 'Watches',
    gender: 'Unisex',
    theme: 'Marvel',
    collection: ['Elite Exclusive'],
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=800'],
    stock: 12,
    rating: 5.0,
    reviewsCount: 12,
    tags: ['marvel', 'ironman', 'tech'],
    sellerId: 's-1'
  },
  {
    id: 'acc-2',
    title: 'Wayne Tech Aviators',
    description: 'Matte black polarized sunglasses with tactical hinges.',
    price: 5999,
    membershipPrice: 4999,
    category: 'Sunglasses',
    gender: 'Men',
    theme: 'DC Comics',
    collection: ['Trending'],
    images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&q=80&w=800'],
    stock: 25,
    rating: 4.8,
    reviewsCount: 95,
    tags: ['dc', 'batman', 'eyewear'],
    sellerId: 's-2'
  },
  ...Array.from({ length: 8 }).map((_, i) => ({
    id: `acc-auto-${i}`,
    title: `Fandom Heritage Accessory ${i + 3}`,
    description: 'Crafted from sustainable materials with unique thematic detailing.',
    price: 2999 + i * 200,
    membershipPrice: 2399 + i * 150,
    category: 'Accessories' as const,
    gender: 'Unisex' as const,
    theme: 'Harry Potter' as const,
    collection: ['Trending' as const],
    images: ['https://images.unsplash.com/photo-1511499767390-90342f16b147?auto=format&fit=crop&q=80&w=800'],
    stock: 100,
    rating: 4.5,
    reviewsCount: 40,
    tags: ['accessories', 'style'],
    sellerId: 's-2'
  })),

  // --- APPAREL (MOCK SAMPLES) ---
  {
    id: 'm-ot-1',
    title: 'Spider-Man: Beyond Stealth',
    description: 'Heavyweight oversized tee with 3D embossed Spider-logo.',
    price: 1299,
    membershipPrice: 999,
    category: 'Oversized Tees',
    gender: 'Men',
    theme: 'Marvel',
    collection: ['Trending', 'Bestsellers'],
    images: ['https://images.unsplash.com/photo-1576871333020-2219d51cca94?auto=format&fit=crop&q=80&w=800'],
    stock: 150,
    rating: 4.9,
    reviewsCount: 1240,
    tags: ['marvel', 'spiderman', 'oversized'],
    colors: ['Midnight Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    sellerId: 's-1'
  },
  {
    id: 'w-d-1',
    title: 'Wonder Woman: Amazonian Grace',
    description: 'Elegant wrap dress featuring subtle gold tiara embroidery.',
    price: 2499,
    membershipPrice: 1999,
    category: 'Dresses',
    gender: 'Women',
    theme: 'DC Comics',
    collection: ['Trending'],
    images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&q=80&w=800'],
    stock: 45,
    rating: 5.0,
    reviewsCount: 112,
    tags: ['dc', 'wonderwoman', 'dress'],
    colors: ['Deep Red', 'Royal Blue'],
    sizes: ['XS', 'S', 'M', 'L'],
    sellerId: 's-2'
  },
];

export const THEME_COLORS = {
  primary: '#e11d48',
  secondary: '#0f172a',
  accent: '#fbbf24',
};
