import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  // --- CLOTHES (10 Products) ---
  {
    id: 'c-1',
    title: 'Minimalist Cotton Tee',
    description: 'High-quality 100% organic cotton t-shirt for daily wear. Breathable and soft.',
    price: 1.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800'],
    stock: 50,
    rating: 4.8,
    reviewsCount: 120,
    tags: ['essential', 'organic', 'minimalist'],
    colors: ['White', 'Black', 'Heather Gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    sellerId: 's-1'
  },
  {
    id: 'c-2',
    title: 'Cargo Tech Pants',
    description: 'Water-resistant utility pants with 6 pockets. Perfect for urban explorers.',
    price: 1.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&q=80&w=800'],
    stock: 30,
    rating: 4.6,
    reviewsCount: 56,
    tags: ['techwear', 'outdoor', 'utility'],
    colors: ['Olive', 'Midnight Black', 'Slate'],
    sizes: ['30', '32', '34', '36'],
    sellerId: 's-1'
  },
  {
    id: 'c-3',
    title: 'Oversized Urban Hoodie',
    description: 'Heavyweight fleece hoodie with a relaxed fit. Ultra-comfortable for lounging or street style.',
    price: 1.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800'],
    stock: 60,
    rating: 4.7,
    reviewsCount: 95,
    tags: ['streetwear', 'comfort', 'fleece'],
    colors: ['Cream', 'Dusty Rose', 'Forest Green'],
    sizes: ['S', 'M', 'L', 'XL'],
    sellerId: 's-1'
  },
  {
    id: 'c-4',
    title: 'Vintage Denim Jacket',
    description: 'Classic distressed denim jacket. A timeless piece that gets better with age.',
    price: 1.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1576871333020-2219d51cca94?auto=format&fit=crop&q=80&w=800'],
    stock: 25,
    rating: 4.8,
    reviewsCount: 140,
    tags: ['denim', 'vintage', 'outerwear'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    sellerId: 's-1'
  },
  {
    id: 'c-5',
    title: 'Merino Wool Sweater',
    description: 'Ethically sourced merino wool for ultimate warmth and a premium feel.',
    price: 1.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    rating: 4.9,
    reviewsCount: 42,
    tags: ['wool', 'premium', 'winter'],
    colors: ['Navy', 'Camel', 'Charcoal'],
    sizes: ['S', 'M', 'L'],
    sellerId: 's-2'
  },
  {
    id: 'c-6',
    title: 'Linen Button-Down',
    description: 'Breathable European linen shirt, perfect for summer nights and vacations.',
    price: 1.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=800'],
    stock: 40,
    rating: 4.5,
    reviewsCount: 88,
    tags: ['linen', 'vacation', 'smart'],
    colors: ['Sky Blue', 'White', 'Sage'],
    sizes: ['M', 'L', 'XL'],
    sellerId: 's-1'
  },
  {
    id: 'c-7',
    title: 'Tailored Chino Shorts',
    description: 'Stretch-cotton chinos with a tailored fit. Versatile for any casual look.',
    price: 1.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&q=80&w=800'],
    stock: 100,
    rating: 4.6,
    reviewsCount: 210,
    tags: ['summer', 'casual', 'chinos'],
    sellerId: 's-1'
  },
  {
    id: 'c-8',
    title: 'Leather Biker Jacket',
    description: 'Full-grain leather jacket with asymmetrical zipper and quilted panels.',
    price: 1.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=800'],
    stock: 5,
    rating: 5.0,
    reviewsCount: 15,
    tags: ['luxury', 'leather', 'edgy'],
    sellerId: 's-3'
  },
  {
    id: 'c-9',
    title: 'Pleated Midi Skirt',
    description: 'Flowy pleated skirt with an elastic waistband for effortless style.',
    price: 1.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&q=80&w=800'],
    stock: 35,
    rating: 4.7,
    reviewsCount: 62,
    tags: ['feminine', 'pleated', 'chic'],
    sellerId: 's-2'
  },
  {
    id: 'c-10',
    title: 'Performance Gym Tank',
    description: 'Moisture-wicking fabric with four-way stretch for your toughest workouts.',
    price: 1.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&q=80&w=800'],
    stock: 120,
    rating: 4.8,
    reviewsCount: 410,
    tags: ['athletic', 'gym', 'activewear'],
    sellerId: 's-4'
  },

  // --- SHOES (10 Products) ---
  {
    id: 's-1',
    title: 'AeroMax Running Shoes',
    description: 'Lightweight running shoes with advanced cushioning and grip.',
    price: 1.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800'],
    stock: 25,
    rating: 4.9,
    reviewsCount: 85,
    tags: ['performance', 'running', 'sport'],
    colors: ['Neon Blue', 'Charcoal', 'Flash Red'],
    sizes: ['7', '8', '9', '10', '11'],
    sellerId: 's-1'
  },
  {
    id: 's-2',
    title: 'Italian Leather Loafers',
    description: 'Handcrafted leather loafers with a premium finish.',
    price: 1.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=800'],
    stock: 12,
    rating: 4.9,
    reviewsCount: 28,
    tags: ['formal', 'luxury', 'leather'],
    colors: ['Cognac', 'Dark Brown', 'Black'],
    sizes: ['8', '9', '10', '11'],
    sellerId: 's-3'
  },
  {
    id: 's-3',
    title: 'Trail-Blazer Hiking Boots',
    description: 'Rugged, waterproof boots designed for the toughest terrains.',
    price: 1.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1520639889313-7272a74b1c73?auto=format&fit=crop&q=80&w=800'],
    stock: 20,
    rating: 4.7,
    reviewsCount: 64,
    tags: ['outdoor', 'hiking', 'adventure'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    sellerId: 's-4'
  },
  {
    id: 's-4',
    title: 'Cloud-Walk Slippers',
    description: 'Memory foam slippers with a plush lining. Like walking on clouds.',
    price: 1.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&q=80&w=800'],
    stock: 80,
    rating: 4.9,
    reviewsCount: 880,
    tags: ['home', 'comfort', 'soft'],
    sellerId: 's-1'
  },
  {
    id: 's-5',
    title: 'Retro Court Sneakers',
    description: 'Vintage-inspired tennis shoes with modern comfort soles.',
    price: 1.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800'],
    stock: 45,
    rating: 4.8,
    reviewsCount: 320,
    tags: ['casual', 'sneakers', 'retro'],
    sellerId: 's-1'
  },
  {
    id: 's-6',
    title: 'High-Top Skate Shoes',
    description: 'Durable suede uppers with vulcanized rubber soles for maximum grip.',
    price: 1.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=800'],
    stock: 30,
    rating: 4.7,
    reviewsCount: 145,
    tags: ['skate', 'streetwear', 'youth'],
    sellerId: 's-1'
  },
  {
    id: 's-7',
    title: 'Espadrille Wedges',
    description: 'Classic jute-wrapped wedge heels with soft suede ankle straps.',
    price: 1.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    rating: 4.6,
    reviewsCount: 42,
    tags: ['summer', 'wedges', 'evening'],
    sellerId: 's-2'
  },
  {
    id: 's-8',
    title: 'Chelsea Suede Boots',
    description: 'Timeless silhouette with elastic side panels and a pull tab.',
    price: 1.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1560506840-ec148e82a604?auto=format&fit=crop&q=80&w=800'],
    stock: 12,
    rating: 4.9,
    reviewsCount: 56,
    tags: ['boots', 'smart', 'style'],
    sellerId: 's-3'
  },
  {
    id: 's-9',
    title: 'Platform Sandal',
    description: 'Statement platform sandals with cushioned footbeds for all-day comfort.',
    price: 1.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=800'],
    stock: 28,
    rating: 4.4,
    reviewsCount: 89,
    tags: ['platform', 'fashion', 'summer'],
    sellerId: 's-1'
  },
  {
    id: 's-10',
    title: 'Basketball Pro High',
    description: 'Built for the court with lateral support and energy-return technology.',
    price: 1.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1512374382149-4332c6c021f5?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    rating: 4.9,
    reviewsCount: 210,
    tags: ['basketball', 'sports', 'high-top'],
    sellerId: 's-4'
  },

  // --- TOYS (10 Products) ---
  {
    id: 't-1',
    title: 'Retro Robot Toy',
    description: 'Hand-painted tin robot toy. A classic collectible.',
    price: 1.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1558685913-d9198f62e711?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    rating: 4.5,
    reviewsCount: 42,
    tags: ['vintage', 'collectible', 'educational'],
    sellerId: 's-2'
  },
  {
    id: 't-2',
    title: 'Sky-High RC Drone',
    description: '4K camera drone with GPS auto-return.',
    price: 1.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?auto=format&fit=crop&q=80&w=800'],
    stock: 8,
    rating: 4.6,
    reviewsCount: 150,
    tags: ['gadget', 'photography', 'drone'],
    sellerId: 's-4'
  },
  {
    id: 't-3',
    title: 'Magnetic Building Tiles',
    description: '100-piece magnetic tile set for open-ended play.',
    price: 1.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1537754192522-830f362312bf?auto=format&fit=crop&q=80&w=800'],
    stock: 100,
    rating: 4.9,
    reviewsCount: 520,
    tags: ['stem', 'creative', 'toddler'],
    sellerId: 's-2'
  },
  {
    id: 't-4',
    title: 'Educational Wood Blocks',
    description: 'Safe, sustainable wooden blocks for motor skills.',
    price: 1.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800'],
    stock: 40,
    rating: 4.7,
    reviewsCount: 204,
    tags: ['kids', 'educational', 'safe'],
    sellerId: 's-2'
  },
  {
    id: 't-5',
    title: 'Chemistry Lab Set',
    description: 'Real science experiments for young explorers. Includes safety goggles.',
    price: 1.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1530210124550-912dc1381cb8?auto=format&fit=crop&q=80&w=800'],
    stock: 30,
    rating: 4.8,
    reviewsCount: 95,
    tags: ['science', 'stem', 'learning'],
    sellerId: 's-2'
  },
  {
    id: 't-6',
    title: 'Digital Chess Master',
    description: 'Electronic board with built-in AI tutor for all skill levels.',
    price: 1.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1528819622765-d6bca1cb36a7?auto=format&fit=crop&q=80&w=800'],
    stock: 12,
    rating: 4.9,
    reviewsCount: 36,
    tags: ['board-game', 'chess', 'ai'],
    sellerId: 's-4'
  },
  {
    id: 't-7',
    title: 'Eco-Friendly Dollhouse',
    description: 'Made from recycled wood with working solar-powered LED lights.',
    price: 1.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1515488764276-beab7607c1e6?auto=format&fit=crop&q=80&w=800'],
    stock: 10,
    rating: 5.0,
    reviewsCount: 18,
    tags: ['sustainable', 'dollhouse', 'gift'],
    sellerId: 's-2'
  },
  {
    id: 't-8',
    title: 'Marble Run Empire',
    description: 'Huge vertical maze set with gravity loops and light-up marbles.',
    price: 1.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&q=80&w=800'],
    stock: 50,
    rating: 4.7,
    reviewsCount: 140,
    tags: ['maze', 'fun', 'puzzle'],
    sellerId: 's-2'
  },
  {
    id: 't-9',
    title: 'Soft Plush Dinosaur',
    description: 'Giant 3-foot plush T-Rex, incredibly soft and hypoallergenic.',
    price: 1.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1534030347209-467a5b0ad3e6?auto=format&fit=crop&q=80&w=800'],
    stock: 45,
    rating: 4.9,
    reviewsCount: 880,
    tags: ['plush', 'kids', 'bedroom'],
    sellerId: 's-1'
  },
  {
    id: 't-10',
    title: 'Microscope Starter Kit',
    description: 'Up to 1200x magnification with prepared and blank slides.',
    price: 1.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1579389083395-4507e9f4c171?auto=format&fit=crop&q=80&w=800'],
    stock: 20,
    rating: 4.6,
    reviewsCount: 63,
    tags: ['science', 'nature', 'discovery'],
    sellerId: 's-2'
  },

  // --- ACCESSORIES (10 Products) ---
  {
    id: 'a-1',
    title: 'Sapphire Chronograph',
    description: 'Elegant stainless steel watch with sapphire glass.',
    price: 1.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800'],
    stock: 10,
    rating: 5.0,
    reviewsCount: 12,
    tags: ['luxury', 'watch', 'professional'],
    sellerId: 's-3'
  },
  {
    id: 'a-2',
    title: 'Aviator Gold Sunglasses',
    description: 'Classic aviator frames with polarized lenses.',
    price: 1.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1511499767350-a1590fdb2ca1?auto=format&fit=crop&q=80&w=800'],
    stock: 45,
    rating: 4.8,
    reviewsCount: 310,
    tags: ['summer', 'eyewear', 'style'],
    sellerId: 's-1'
  },
  {
    id: 'a-3',
    title: 'Silk Evening Wrap',
    description: 'Luxurious 100% mulberry silk shawl.',
    price: 1.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    rating: 4.4,
    reviewsCount: 18,
    tags: ['silk', 'elegant', 'shawl'],
    sellerId: 's-3'
  },
  {
    id: 'a-4',
    title: 'Minimalist Leather Wallet',
    description: 'Slim bifold wallet made from top-grain leather.',
    price: 1.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800'],
    stock: 55,
    rating: 4.7,
    reviewsCount: 210,
    tags: ['minimalist', 'leather', 'edc'],
    sellerId: 's-1'
  },
  {
    id: 'a-5',
    title: 'Canvas Weekender Bag',
    description: 'Extra-large carryall with leather accents for short trips.',
    price: 1.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800'],
    stock: 20,
    rating: 4.9,
    reviewsCount: 45,
    tags: ['travel', 'bag', 'durable'],
    sellerId: 's-1'
  },
  {
    id: 'a-6',
    title: 'Sterling Silver Hoops',
    description: 'Hypoallergenic classic hoop earrings with a mirror finish.',
    price: 1.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1535633302704-b02f4faad747?auto=format&fit=crop&q=80&w=800'],
    stock: 100,
    rating: 4.8,
    reviewsCount: 190,
    tags: ['jewelry', 'silver', 'classic'],
    sellerId: 's-3'
  },
  {
    id: 'a-7',
    title: 'Leather Tech Sleeve',
    description: 'Padded sleeve fits up to 14" laptops. Pebbled leather finish.',
    price: 1.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&q=80&w=800'],
    stock: 30,
    rating: 4.6,
    reviewsCount: 28,
    tags: ['tech', 'leather', 'protection'],
    sellerId: 's-1'
  },
  {
    id: 'a-8',
    title: 'Weighted Sleep Mask',
    description: 'Infused with lavender and filled with micro-beads for deep rest.',
    price: 1.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1582231243724-18c6439a2b5b?auto=format&fit=crop&q=80&w=800'],
    stock: 80,
    rating: 4.7,
    reviewsCount: 312,
    tags: ['wellness', 'sleep', 'travel'],
    sellerId: 's-4'
  },
  {
    id: 'a-9',
    title: 'Titanium Belt Buckle',
    description: 'Virtually indestructible belt with a lifetime guarantee. Black webbing.',
    price: 1.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1624222247344-550fbadec67f?auto=format&fit=crop&q=80&w=800'],
    stock: 45,
    rating: 4.8,
    reviewsCount: 112,
    tags: ['durable', 'belt', 'outdoor'],
    sellerId: 's-4'
  },
  {
    id: 'a-10',
    title: 'Merino Wool Scarf',
    description: 'Extra-long oversized scarf in a classic herringbone pattern.',
    price: 1.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&q=80&w=800'],
    stock: 60,
    rating: 4.9,
    reviewsCount: 88,
    tags: ['winter', 'wool', 'warm'],
    sellerId: 's-2'
  }
];

export const THEME_COLORS = {
  primary: '#6366f1', // Indigo 500
  secondary: '#0f172a', // Slate 900
  accent: '#f59e0b', // Amber 500
};
