import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  // --- CLOTHES (20 Products) ---
  {
    id: 'c-1',
    title: 'Minimalist Cotton Tee',
    description: 'High-quality 100% organic cotton t-shirt for daily wear. Breathable and soft.',
    price: 29.99,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=800'],
    stock: 50,
    rating: 4.8,
    reviewsCount: 120,
    tags: ['essential', 'organic', 'minimalist'],
    colors: ['White', 'Black', 'Heather Gray'],
    sizes: ['S', 'M', 'L', 'XL'],
    sellerId: 's-1'
  },
  {
    id: 'c-2',
    title: 'Cargo Tech Pants',
    description: 'Water-resistant utility pants with 6 pockets. Perfect for urban explorers.',
    price: 89.50,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&q=80&w=800'],
    stock: 30,
    rating: 4.6,
    reviewsCount: 56,
    tags: ['techwear', 'outdoor', 'utility'],
    colors: ['Olive', 'Midnight Black', 'Slate'],
    sizes: ['30', '32', '34', '36'],
    sellerId: 's-1'
  },
  {
    id: 'c-3',
    title: 'Oversized Urban Hoodie',
    description: 'Heavyweight fleece hoodie with a relaxed fit. Ultra-comfortable for lounging or street style.',
    price: 65.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800'],
    stock: 60,
    rating: 4.7,
    reviewsCount: 95,
    tags: ['streetwear', 'comfort', 'fleece'],
    colors: ['Cream', 'Dusty Rose', 'Forest Green'],
    sizes: ['S', 'M', 'L', 'XL'],
    sellerId: 's-1'
  },
  {
    id: 'c-4',
    title: 'Vintage Denim Jacket',
    description: 'Classic distressed denim jacket. A timeless piece that gets better with age.',
    price: 110.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1576871333020-2219d51cca94?auto=format&fit=crop&q=80&w=800'],
    stock: 25,
    rating: 4.8,
    reviewsCount: 140,
    tags: ['denim', 'vintage', 'outerwear'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    sellerId: 's-1'
  },
  {
    id: 'c-5',
    title: 'Merino Wool Sweater',
    description: 'Ethically sourced merino wool for ultimate warmth and a premium feel.',
    price: 120.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    rating: 4.9,
    reviewsCount: 42,
    tags: ['wool', 'premium', 'winter'],
    colors: ['Navy', 'Camel', 'Charcoal'],
    sizes: ['S', 'M', 'L'],
    sellerId: 's-2'
  },
  {
    id: 'c-6',
    title: 'Linen Button-Down',
    description: 'Breathable European linen shirt, perfect for summer nights and vacations.',
    price: 75.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=800'],
    stock: 40,
    rating: 4.5,
    reviewsCount: 88,
    tags: ['linen', 'vacation', 'smart'],
    colors: ['Sky Blue', 'White', 'Sage'],
    sizes: ['M', 'L', 'XL'],
    sellerId: 's-1'
  },
  {
    id: 'c-7',
    title: 'Tailored Chino Shorts',
    description: 'Stretch-cotton chinos with a tailored fit. Versatile for any casual look.',
    price: 45.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&q=80&w=800'],
    stock: 100,
    rating: 4.6,
    reviewsCount: 210,
    tags: ['summer', 'casual', 'chinos'],
    sellerId: 's-1'
  },
  {
    id: 'c-8',
    title: 'Leather Biker Jacket',
    description: 'Full-grain leather jacket with asymmetrical zipper and quilted panels.',
    price: 350.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=800'],
    stock: 5,
    rating: 5.0,
    reviewsCount: 15,
    tags: ['luxury', 'leather', 'edgy'],
    sellerId: 's-3'
  },
  {
    id: 'c-9',
    title: 'Pleated Midi Skirt',
    description: 'Flowy pleated skirt with an elastic waistband for effortless style.',
    price: 55.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&q=80&w=800'],
    stock: 35,
    rating: 4.7,
    reviewsCount: 62,
    tags: ['feminine', 'pleated', 'chic'],
    sellerId: 's-2'
  },
  {
    id: 'c-10',
    title: 'Performance Gym Tank',
    description: 'Moisture-wicking fabric with four-way stretch for your toughest workouts.',
    price: 32.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&q=80&w=800'],
    stock: 120,
    rating: 4.8,
    reviewsCount: 410,
    tags: ['athletic', 'gym', 'activewear'],
    sellerId: 's-4'
  },
  {
    id: 'c-11',
    title: 'Sherpa-Lined Trucker',
    description: 'Classic trucker jacket with a warm faux-sherpa lining. Built for durability.',
    price: 135.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=800'],
    stock: 18,
    rating: 4.8,
    reviewsCount: 34,
    tags: ['winter', 'rugged', 'warm'],
    sellerId: 's-1'
  },
  {
    id: 'c-12',
    title: 'Graphic Print Tee',
    description: 'Artist-designed graphics on premium combed cotton. Limited edition drop.',
    price: 38.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&q=80&w=800'],
    stock: 45,
    rating: 4.6,
    reviewsCount: 112,
    tags: ['graphic', 'streetwear', 'art'],
    sellerId: 's-1'
  },
  {
    id: 'c-13',
    title: 'High-Waist Yoga Leggings',
    description: 'Buttery soft fabric that feels like a second skin. Squat-proof design.',
    price: 68.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&q=80&w=800'],
    stock: 85,
    rating: 4.9,
    reviewsCount: 650,
    tags: ['yoga', 'activewear', 'comfortable'],
    sellerId: 's-4'
  },
  {
    id: 'c-14',
    title: 'Quilted Puffer Vest',
    description: 'Water-resistant outer shell with down insulation. The perfect layering piece.',
    price: 95.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1539533397308-a61ef8712398?auto=format&fit=crop&q=80&w=800'],
    stock: 22,
    rating: 4.7,
    reviewsCount: 29,
    tags: ['outdoor', 'layering', 'warm'],
    sellerId: 's-2'
  },
  {
    id: 'c-15',
    title: 'Flannel Plaid Shirt',
    description: 'Double-brushed flannel for extra softness. A fall wardrobe staple.',
    price: 48.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?auto=format&fit=crop&q=80&w=800'],
    stock: 70,
    rating: 4.5,
    reviewsCount: 180,
    tags: ['casual', 'plaid', 'fall'],
    sellerId: 's-1'
  },
  {
    id: 'c-16',
    title: 'Cashmere Beanie',
    description: '100% pure cashmere beanie. Unmatched softness for chilly mornings.',
    price: 45.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&q=80&w=800'],
    stock: 40,
    rating: 4.9,
    reviewsCount: 82,
    tags: ['cashmere', 'winter', 'accessory'],
    sellerId: 's-3'
  },
  {
    id: 'c-17',
    title: 'Relaxed Joggers',
    description: 'Premium cotton-poly blend joggers with tapered cuffs and deep pockets.',
    price: 52.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&q=80&w=800'],
    stock: 55,
    rating: 4.7,
    reviewsCount: 94,
    tags: ['loungewear', 'casual', 'joggers'],
    sellerId: 's-1'
  },
  {
    id: 'c-18',
    title: 'Satin Slip Dress',
    description: 'Lustrous satin midi dress with adjustable spaghetti straps.',
    price: 88.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&q=80&w=800'],
    stock: 12,
    rating: 4.8,
    reviewsCount: 31,
    tags: ['formal', 'satin', 'elegant'],
    sellerId: 's-2'
  },
  {
    id: 'c-19',
    title: 'Waterproof Rain Parka',
    description: 'Seam-sealed parka with an adjustable hood to keep you dry in style.',
    price: 180.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1544923246-77307dd654ca?auto=format&fit=crop&q=80&w=800'],
    stock: 10,
    rating: 4.7,
    reviewsCount: 22,
    tags: ['outdoor', 'rain', 'techwear'],
    sellerId: 's-4'
  },
  {
    id: 'c-20',
    title: 'Corduroy Overshirt',
    description: 'Fine-wale corduroy shirt that works perfectly as a light jacket.',
    price: 72.00,
    category: 'Clothes',
    images: ['https://images.unsplash.com/photo-1594932224828-b4b059b8fe0e?auto=format&fit=crop&q=80&w=800'],
    stock: 30,
    rating: 4.6,
    reviewsCount: 47,
    tags: ['casual', 'corduroy', 'style'],
    sellerId: 's-1'
  },

  // --- SHOES (20 Products) ---
  {
    id: 's-1',
    title: 'AeroMax Running Shoes',
    description: 'Lightweight running shoes with advanced cushioning and grip.',
    price: 129.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800'],
    stock: 25,
    rating: 4.9,
    reviewsCount: 85,
    tags: ['performance', 'running', 'sport'],
    colors: ['Neon Blue', 'Charcoal', 'Flash Red'],
    sizes: ['7', '8', '9', '10', '11'],
    sellerId: 's-1'
  },
  {
    id: 's-2',
    title: 'Italian Leather Loafers',
    description: 'Handcrafted leather loafers with a premium finish.',
    price: 155.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=800'],
    stock: 12,
    rating: 4.9,
    reviewsCount: 28,
    tags: ['formal', 'luxury', 'leather'],
    colors: ['Cognac', 'Dark Brown', 'Black'],
    sizes: ['8', '9', '10', '11'],
    sellerId: 's-3'
  },
  {
    id: 's-3',
    title: 'Trail-Blazer Hiking Boots',
    description: 'Rugged, waterproof boots designed for the toughest terrains.',
    price: 175.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1520639889313-7272a74b1c73?auto=format&fit=crop&q=80&w=800'],
    stock: 20,
    rating: 4.7,
    reviewsCount: 64,
    tags: ['outdoor', 'hiking', 'adventure'],
    sizes: ['7', '8', '9', '10', '11', '12'],
    sellerId: 's-4'
  },
  {
    id: 's-4',
    title: 'Cloud-Walk Slippers',
    description: 'Memory foam slippers with a plush lining. Like walking on clouds.',
    price: 35.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&q=80&w=800'],
    stock: 80,
    rating: 4.9,
    reviewsCount: 880,
    tags: ['home', 'comfort', 'soft'],
    sellerId: 's-1'
  },
  {
    id: 's-5',
    title: 'Retro Court Sneakers',
    description: 'Vintage-inspired tennis shoes with modern comfort soles.',
    price: 85.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=800'],
    stock: 45,
    rating: 4.8,
    reviewsCount: 320,
    tags: ['casual', 'sneakers', 'retro'],
    sellerId: 's-1'
  },
  {
    id: 's-6',
    title: 'High-Top Skate Shoes',
    description: 'Durable suede uppers with vulcanized rubber soles for maximum grip.',
    price: 78.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=800'],
    stock: 30,
    rating: 4.7,
    reviewsCount: 145,
    tags: ['skate', 'streetwear', 'youth'],
    sellerId: 's-1'
  },
  {
    id: 's-7',
    title: 'Espadrille Wedges',
    description: 'Classic jute-wrapped wedge heels with soft suede ankle straps.',
    price: 92.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    rating: 4.6,
    reviewsCount: 42,
    tags: ['summer', 'wedges', 'evening'],
    sellerId: 's-2'
  },
  {
    id: 's-8',
    title: 'Chelsea Suede Boots',
    description: 'Timeless silhouette with elastic side panels and a pull tab.',
    price: 160.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1560506840-ec148e82a604?auto=format&fit=crop&q=80&w=800'],
    stock: 12,
    rating: 4.9,
    reviewsCount: 56,
    tags: ['boots', 'smart', 'style'],
    sellerId: 's-3'
  },
  {
    id: 's-9',
    title: 'Platform Sandal',
    description: 'Statement platform sandals with cushioned footbeds for all-day comfort.',
    price: 65.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=800'],
    stock: 28,
    rating: 4.4,
    reviewsCount: 89,
    tags: ['platform', 'fashion', 'summer'],
    sellerId: 's-1'
  },
  {
    id: 's-10',
    title: 'Basketball Pro High',
    description: 'Built for the court with lateral support and energy-return technology.',
    price: 145.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1512374382149-4332c6c021f5?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    rating: 4.9,
    reviewsCount: 210,
    tags: ['basketball', 'sports', 'high-top'],
    sellerId: 's-4'
  },
  {
    id: 's-11',
    title: 'Eco-Knit Trainers',
    description: 'Upper made entirely from recycled plastic bottles. Ultra-breathable.',
    price: 98.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&q=80&w=800'],
    stock: 50,
    rating: 4.7,
    reviewsCount: 178,
    tags: ['sustainable', 'vegan', 'lifestyle'],
    sellerId: 's-1'
  },
  {
    id: 's-12',
    title: 'Pointed Toe Stilettos',
    description: 'High-gloss patent leather with a sleek stiletto heel for formal glamour.',
    price: 185.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?auto=format&fit=crop&q=80&w=800'],
    stock: 10,
    rating: 4.8,
    reviewsCount: 22,
    tags: ['formal', 'luxury', 'heels'],
    sellerId: 's-3'
  },
  {
    id: 's-13',
    title: 'All-Terrain Sandals',
    description: 'Quick-dry straps with a rugged sole for beach and trail adventures.',
    price: 58.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1562273103-91206b930564?auto=format&fit=crop&q=80&w=800'],
    stock: 65,
    rating: 4.6,
    reviewsCount: 134,
    tags: ['outdoor', 'travel', 'sandals'],
    sellerId: 's-4'
  },
  {
    id: 's-14',
    title: 'Classic Brogues',
    description: 'Full-grain leather with traditional wingtip perforation details.',
    price: 140.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=800'],
    stock: 20,
    rating: 4.8,
    reviewsCount: 45,
    tags: ['formal', 'brogues', 'leather'],
    sellerId: 's-3'
  },
  {
    id: 's-15',
    title: 'Waterproof Deck Shoes',
    description: 'Non-slip rubber soles with salt-resistant leather uppers.',
    price: 115.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&q=80&w=800'],
    stock: 25,
    rating: 4.7,
    reviewsCount: 38,
    tags: ['sailing', 'casual', 'preppy'],
    sellerId: 's-1'
  },
  {
    id: 's-16',
    title: 'Canvas High-Tops',
    description: 'The iconic silhouette in a range of seasonal colors.',
    price: 65.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800'],
    stock: 100,
    rating: 4.8,
    reviewsCount: 1520,
    tags: ['canvas', 'classic', 'casual'],
    sellerId: 's-1'
  },
  {
    id: 's-17',
    title: 'Winter Snow Boots',
    description: 'Insulated with faux fur and heavy-duty tread for ice and snow.',
    price: 155.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1549476464-37392f71755a?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    rating: 4.7,
    reviewsCount: 92,
    tags: ['winter', 'boots', 'waterproof'],
    sellerId: 's-4'
  },
  {
    id: 's-18',
    title: 'Penny Loafers',
    description: 'Refined casual shoe in soft matte leather.',
    price: 125.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&q=80&w=800'],
    stock: 18,
    rating: 4.6,
    reviewsCount: 28,
    tags: ['smart-casual', 'loafers', 'leather'],
    sellerId: 's-3'
  },
  {
    id: 's-19',
    title: 'Running Spikes',
    description: 'Track-ready spikes for elite sprinters. Ultralight composite plate.',
    price: 165.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800'],
    stock: 8,
    rating: 5.0,
    reviewsCount: 14,
    tags: ['track', 'racing', 'athletics'],
    sellerId: 's-4'
  },
  {
    id: 's-20',
    title: 'Mule Flats',
    description: 'Easy-on, easy-off comfort with a sharp pointed-toe look.',
    price: 75.00,
    category: 'Shoes',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&q=80&w=800'],
    stock: 40,
    rating: 4.5,
    reviewsCount: 56,
    tags: ['flats', 'workwear', 'comfy'],
    sellerId: 's-2'
  },

  // --- TOYS (20 Products) ---
  {
    id: 't-1',
    title: 'Retro Robot Toy',
    description: 'Hand-painted tin robot toy. A classic collectible.',
    price: 45.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1558685913-d9198f62e711?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    rating: 4.5,
    reviewsCount: 42,
    tags: ['vintage', 'collectible', 'educational'],
    sellerId: 's-2'
  },
  {
    id: 't-2',
    title: 'Sky-High RC Drone',
    description: '4K camera drone with GPS auto-return.',
    price: 299.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1507582020474-9a35b7d455d9?auto=format&fit=crop&q=80&w=800'],
    stock: 8,
    rating: 4.6,
    reviewsCount: 150,
    tags: ['gadget', 'photography', 'drone'],
    sellerId: 's-4'
  },
  {
    id: 't-3',
    title: 'Magnetic Building Tiles',
    description: '100-piece magnetic tile set for open-ended play.',
    price: 59.99,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1537754192522-830f362312bf?auto=format&fit=crop&q=80&w=800'],
    stock: 100,
    rating: 4.9,
    reviewsCount: 520,
    tags: ['stem', 'creative', 'toddler'],
    sellerId: 's-2'
  },
  {
    id: 't-4',
    title: 'Educational Wood Blocks',
    description: 'Safe, sustainable wooden blocks for motor skills.',
    price: 34.99,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&q=80&w=800'],
    stock: 40,
    rating: 4.7,
    reviewsCount: 204,
    tags: ['kids', 'educational', 'safe'],
    sellerId: 's-2'
  },
  {
    id: 't-5',
    title: 'Chemistry Lab Set',
    description: 'Real science experiments for young explorers. Includes safety goggles.',
    price: 42.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1530210124550-912dc1381cb8?auto=format&fit=crop&q=80&w=800'],
    stock: 30,
    rating: 4.8,
    reviewsCount: 95,
    tags: ['science', 'stem', 'learning'],
    sellerId: 's-2'
  },
  {
    id: 't-6',
    title: 'Digital Chess Master',
    description: 'Electronic board with built-in AI tutor for all skill levels.',
    price: 110.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1528819622765-d6bca1cb36a7?auto=format&fit=crop&q=80&w=800'],
    stock: 12,
    rating: 4.9,
    reviewsCount: 36,
    tags: ['board-game', 'chess', 'ai'],
    sellerId: 's-4'
  },
  {
    id: 't-7',
    title: 'Eco-Friendly Dollhouse',
    description: 'Made from recycled wood with working solar-powered LED lights.',
    price: 145.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1515488764276-beab7607c1e6?auto=format&fit=crop&q=80&w=800'],
    stock: 10,
    rating: 5.0,
    reviewsCount: 18,
    tags: ['sustainable', 'dollhouse', 'gift'],
    sellerId: 's-2'
  },
  {
    id: 't-8',
    title: 'Marble Run Empire',
    description: 'Huge vertical maze set with gravity loops and light-up marbles.',
    price: 55.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&q=80&w=800'],
    stock: 50,
    rating: 4.7,
    reviewsCount: 140,
    tags: ['maze', 'fun', 'puzzle'],
    sellerId: 's-2'
  },
  {
    id: 't-9',
    title: 'Soft Plush Dinosaur',
    description: 'Giant 3-foot plush T-Rex, incredibly soft and hypoallergenic.',
    price: 48.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1534030347209-467a5b0ad3e6?auto=format&fit=crop&q=80&w=800'],
    stock: 45,
    rating: 4.9,
    reviewsCount: 880,
    tags: ['plush', 'kids', 'bedroom'],
    sellerId: 's-1'
  },
  {
    id: 't-10',
    title: 'Microscope Starter Kit',
    description: 'Up to 1200x magnification with prepared and blank slides.',
    price: 78.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1579389083395-4507e9f4c171?auto=format&fit=crop&q=80&w=800'],
    stock: 20,
    rating: 4.6,
    reviewsCount: 63,
    tags: ['science', 'nature', 'discovery'],
    sellerId: 's-2'
  },
  {
    id: 't-11',
    title: 'Solar System Projector',
    description: 'Rotates 360 degrees and projects 8 planets onto your ceiling.',
    price: 39.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1454789548928-9efd52dc4031?auto=format&fit=crop&q=80&w=800'],
    stock: 85,
    rating: 4.4,
    reviewsCount: 245,
    tags: ['space', 'education', 'light'],
    sellerId: 's-4'
  },
  {
    id: 't-12',
    title: 'Code-A-Caterpillar',
    description: 'Introduces basic programming concepts through physical play.',
    price: 64.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1560343060-c142ba36fa3e?auto=format&fit=crop&q=80&w=800'],
    stock: 30,
    rating: 4.8,
    reviewsCount: 110,
    tags: ['coding', 'stem', 'preschool'],
    sellerId: 's-2'
  },
  {
    id: 't-13',
    title: 'Indoor Climbing Arch',
    description: 'Montessori-inspired wooden arch for developing balance and motor skills.',
    price: 185.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&q=80&w=800'],
    stock: 8,
    rating: 4.9,
    reviewsCount: 42,
    tags: ['active', 'montessori', 'wood'],
    sellerId: 's-2'
  },
  {
    id: 't-14',
    title: 'Strategy Card Game',
    description: 'Award-winning fantasy deck-builder for 2-4 players.',
    price: 25.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1610812383741-6e82811d739b?auto=format&fit=crop&q=80&w=800'],
    stock: 150,
    rating: 4.7,
    reviewsCount: 320,
    tags: ['cards', 'strategy', 'games'],
    sellerId: 's-1'
  },
  {
    id: 't-15',
    title: 'Canvas Play Tent',
    description: 'Portable teepee for indoor and outdoor adventures. Easy assembly.',
    price: 88.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1560343776-97e7d202ff0e?auto=format&fit=crop&q=80&w=800'],
    stock: 25,
    rating: 4.8,
    reviewsCount: 156,
    tags: ['play', 'outdoor', 'indoor'],
    sellerId: 's-1'
  },
  {
    id: 't-16',
    title: 'Remote Control Rally Car',
    description: '1:12 scale with independent suspension and 25km/h top speed.',
    price: 95.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?auto=format&fit=crop&q=80&w=800'],
    stock: 18,
    rating: 4.5,
    reviewsCount: 88,
    tags: ['racing', 'rc-car', 'hobby'],
    sellerId: 's-4'
  },
  {
    id: 't-17',
    title: 'Giant Bubble Maker',
    description: 'Create bubbles larger than a person with our special solution wand.',
    price: 18.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1551352826-6458577dd83b?auto=format&fit=crop&q=80&w=800'],
    stock: 200,
    rating: 4.6,
    reviewsCount: 1100,
    tags: ['outdoor', 'bubbles', 'summer'],
    sellerId: 's-1'
  },
  {
    id: 't-18',
    title: 'Piano Learning Pad',
    description: 'Touch-sensitive giant floor mat for teaching music fundamentals.',
    price: 52.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1514119412350-e174d90d280e?auto=format&fit=crop&q=80&w=800'],
    stock: 35,
    rating: 4.7,
    reviewsCount: 92,
    tags: ['music', 'floor-mat', 'learning'],
    sellerId: 's-2'
  },
  {
    id: 't-19',
    title: 'Historical Puzzle Set',
    description: '1000-piece puzzle depicting ancient wonders of the world.',
    price: 22.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1585338663460-7040149e648a?auto=format&fit=crop&q=80&w=800'],
    stock: 75,
    rating: 4.8,
    reviewsCount: 56,
    tags: ['puzzle', 'history', 'leisure'],
    sellerId: 's-1'
  },
  {
    id: 't-20',
    title: 'Model Rocket Kit',
    description: 'Complete set to build and launch a rocket up to 500 feet.',
    price: 49.00,
    category: 'Toys',
    images: ['https://images.unsplash.com/photo-1541447271487-09612b3f49f7?auto=format&fit=crop&q=80&w=800'],
    stock: 14,
    rating: 4.9,
    reviewsCount: 38,
    tags: ['science', 'launch', 'hobby'],
    sellerId: 's-4'
  },

  // --- ACCESSORIES (20 Products) ---
  {
    id: 'a-1',
    title: 'Sapphire Chronograph',
    description: 'Elegant stainless steel watch with sapphire glass.',
    price: 199.99,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800'],
    stock: 10,
    rating: 5.0,
    reviewsCount: 12,
    tags: ['luxury', 'watch', 'professional'],
    sellerId: 's-3'
  },
  {
    id: 'a-2',
    title: 'Aviator Gold Sunglasses',
    description: 'Classic aviator frames with polarized lenses.',
    price: 75.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1511499767350-a1590fdb2ca1?auto=format&fit=crop&q=80&w=800'],
    stock: 45,
    rating: 4.8,
    reviewsCount: 310,
    tags: ['summer', 'eyewear', 'style'],
    sellerId: 's-1'
  },
  {
    id: 'a-3',
    title: 'Silk Evening Wrap',
    description: 'Luxurious 100% mulberry silk shawl.',
    price: 85.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&q=80&w=800'],
    stock: 15,
    rating: 4.4,
    reviewsCount: 18,
    tags: ['silk', 'elegant', 'shawl'],
    sellerId: 's-3'
  },
  {
    id: 'a-4',
    title: 'Minimalist Leather Wallet',
    description: 'Slim bifold wallet made from top-grain leather.',
    price: 49.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800'],
    stock: 55,
    rating: 4.7,
    reviewsCount: 210,
    tags: ['minimalist', 'leather', 'edc'],
    sellerId: 's-1'
  },
  {
    id: 'a-5',
    title: 'Canvas Weekender Bag',
    description: 'Extra-large carryall with leather accents for short trips.',
    price: 125.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800'],
    stock: 20,
    rating: 4.9,
    reviewsCount: 45,
    tags: ['travel', 'bag', 'durable'],
    sellerId: 's-1'
  },
  {
    id: 'a-6',
    title: 'Sterling Silver Hoops',
    description: 'Hypoallergenic classic hoop earrings with a mirror finish.',
    price: 35.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1535633302704-b02f4faad747?auto=format&fit=crop&q=80&w=800'],
    stock: 100,
    rating: 4.8,
    reviewsCount: 190,
    tags: ['jewelry', 'silver', 'classic'],
    sellerId: 's-3'
  },
  {
    id: 'a-7',
    title: 'Leather Tech Sleeve',
    description: 'Padded sleeve fits up to 14" laptops. Pebbled leather finish.',
    price: 65.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&q=80&w=800'],
    stock: 30,
    rating: 4.6,
    reviewsCount: 28,
    tags: ['tech', 'leather', 'protection'],
    sellerId: 's-1'
  },
  {
    id: 'a-8',
    title: 'Weighted Sleep Mask',
    description: 'Infused with lavender and filled with micro-beads for deep rest.',
    price: 28.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1582231243724-18c6439a2b5b?auto=format&fit=crop&q=80&w=800'],
    stock: 80,
    rating: 4.7,
    reviewsCount: 312,
    tags: ['wellness', 'sleep', 'travel'],
    sellerId: 's-4'
  },
  {
    id: 'a-9',
    title: 'Titanium Belt Buckle',
    description: 'Virtually indestructible belt with a lifetime guarantee. Black webbing.',
    price: 42.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1624222247344-550fbadec67f?auto=format&fit=crop&q=80&w=800'],
    stock: 45,
    rating: 4.8,
    reviewsCount: 112,
    tags: ['durable', 'belt', 'outdoor'],
    sellerId: 's-4'
  },
  {
    id: 'a-10',
    title: 'Merino Wool Scarf',
    description: 'Extra-long oversized scarf in a classic herringbone pattern.',
    price: 58.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&q=80&w=800'],
    stock: 60,
    rating: 4.9,
    reviewsCount: 88,
    tags: ['winter', 'wool', 'warm'],
    sellerId: 's-2'
  },
  {
    id: 'a-11',
    title: 'Blue Light Glasses',
    description: 'Reduce eye strain from screen time. Stylish unisex frames.',
    price: 39.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1574258495973-f010dfbb5371?auto=format&fit=crop&q=80&w=800'],
    stock: 150,
    rating: 4.5,
    reviewsCount: 420,
    tags: ['tech', 'eyewear', 'health'],
    sellerId: 's-1'
  },
  {
    id: 'a-12',
    title: 'Suede Crossbody Bag',
    description: 'Tassel details and gold hardware. Perfect for hands-free shopping.',
    price: 110.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&q=80&w=800'],
    stock: 12,
    rating: 4.7,
    reviewsCount: 22,
    tags: ['fashion', 'bag', 'suede'],
    sellerId: 's-3'
  },
  {
    id: 'a-13',
    title: 'Magnetic Hat Clip',
    description: 'Keep your hat secure on your bag while traveling. Heavy duty magnet.',
    price: 15.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1533055640609-24b498dfd74c?auto=format&fit=crop&q=80&w=800'],
    stock: 300,
    rating: 4.8,
    reviewsCount: 115,
    tags: ['travel', 'utility', 'gift'],
    sellerId: 's-1'
  },
  {
    id: 'a-14',
    title: 'Gold Linked Bracelet',
    description: '14k gold-plated chunky link bracelet. Adjustable length.',
    price: 48.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800'],
    stock: 40,
    rating: 4.6,
    reviewsCount: 54,
    tags: ['jewelry', 'gold', 'fashion'],
    sellerId: 's-3'
  },
  {
    id: 'a-15',
    title: 'Nylon Travel Pouch',
    description: 'Organizational set of 3 pouches for electronics and cables.',
    price: 32.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1511405946472-a37e3b5ccd47?auto=format&fit=crop&q=80&w=800'],
    stock: 100,
    rating: 4.7,
    reviewsCount: 198,
    tags: ['organization', 'travel', 'tech'],
    sellerId: 's-1'
  },
  {
    id: 'a-16',
    title: 'Pearl Hair Clip Set',
    description: 'Set of 4 elegant clips with hand-set simulated pearls.',
    price: 18.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1581044777550-4cfa60707c33?auto=format&fit=crop&q=80&w=800'],
    stock: 250,
    rating: 4.5,
    reviewsCount: 62,
    tags: ['hair', 'pearl', 'pretty'],
    sellerId: 's-2'
  },
  {
    id: 'a-17',
    title: 'RFID Blocking Passport Holder',
    description: 'Soft pebbled leather with 4 card slots and boarding pass pocket.',
    price: 25.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1563906267088-b02d56a29cd6?auto=format&fit=crop&q=80&w=800'],
    stock: 85,
    rating: 4.9,
    reviewsCount: 412,
    tags: ['travel', 'security', 'leather'],
    sellerId: 's-1'
  },
  {
    id: 'a-18',
    title: 'Woven Straw Hat',
    description: 'Wide brim sun hat with an adjustable inner strap for windy days.',
    price: 42.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1521316730702-829ad88e7ff7?auto=format&fit=crop&q=80&w=800'],
    stock: 45,
    rating: 4.6,
    reviewsCount: 83,
    tags: ['summer', 'hat', 'vacation'],
    sellerId: 's-2'
  },
  {
    id: 'a-19',
    title: 'Yoga Mat Carrier',
    description: 'Cotton canvas strap with embroidered details. Fits any mat size.',
    price: 19.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800'],
    stock: 60,
    rating: 4.8,
    reviewsCount: 122,
    tags: ['yoga', 'fitness', 'bag'],
    sellerId: 's-4'
  },
  {
    id: 'a-20',
    title: 'Enamel Pin Set',
    description: 'Curated set of 5 modern art inspired enamel pins.',
    price: 22.00,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1591129841117-3adfd313e34f?auto=format&fit=crop&q=80&w=800'],
    stock: 150,
    rating: 4.9,
    reviewsCount: 310,
    tags: ['art', 'pin', 'style'],
    sellerId: 's-1'
  }
];

export const THEME_COLORS = {
  primary: '#6366f1', // Indigo 500
  secondary: '#0f172a', // Slate 900
  accent: '#f59e0b', // Amber 500
};
